#! /usr/bin/env python
import sys
import os
import socket

interface, port, message = sys.argv[1:4]
port = int(port)

sock = socket.socket()

print 'connecting to', interface, port
sock.connect((interface, port))

print 'sending %d bytes' % len(message)
sock.sendall(message)

print 'received:'
x = sock.recv(4096)
print (x,)
