#! /usr/bin/env python
import sys
import os
import socket

interface, port, message = sys.argv[1:4]
port = int(port)

message1 = '1: ' + message
message2 = '2: ' + message

sock1 = socket.socket()
sock2 = socket.socket()

print '1. connecting to', interface, port
sock1.connect((interface, port))

print '2. connecting to', interface, port
sock2.connect((interface, port))

print '1. sending %d bytes' % len(message1)
sock1.sendall(message1)

print '2. sending %d bytes' % len(message2)
sock2.sendall(message2)

print '1. received:', (sock1.recv(4096),)
print '2. received:', (sock2.recv(4096),)
